/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package voedselbanksysteem;

import com.sun.org.apache.xml.internal.dtm.DTM;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Calvin Zeij
 */
public class GegevensUitgiftepunt extends javax.swing.JFrame {

    /**
     * Creates new form GegevensUitgiftepunt
     */
    private Connection connection;
    private Statement statement;
    private ResultSet rs;
    private HomeScreen opener;
    private JDBCDriver driver;
    
    public GegevensUitgiftepunt() {
         try {
            initComponents();
            connection = DatabaseSource.getConnection();
            statement = connection.createStatement();

            
            String query = "SELECT Naam, maximumCapaciteit, count(DISTINCT kaartnr) as 'Huidige clienten',\n" +
"sum(CASE voedselpakketSoort\n" +
"WHEN 'Enkelvoudig pakket' THEN 1\n" +
"WHEN 'Dubbel pakket' THEN 2\n" +
"WHEN '3-voudig pakket' THEN 3 END) as 'Aantal pakketten'\n" +
"                            from Uitgiftepunt join Cliënt c on Naam = toegewezenUitgiftepunt\n" +
"											  join Intake i on kaartnr = Cliënt   \n" +
"                                              where i.StatusIntake = 'actief'\n" +
"											  group by Naam;";
            rs = statement.executeQuery (query);
            // alle nummers van de collom
            
             driver = new JDBCDriver();
             JDBCDriver.fillTable(rs, myTable);
             myTable.getColumnModel().getColumn(0).setHeaderValue("Uitgiftepunt");
             myTable.getColumnModel().getColumn(1).setHeaderValue("Maximum Capaciteit");
             myTable.getColumnModel().getColumn(2).setHeaderValue("Huidige cliënt");
             myTable.getColumnModel().getColumn(3).setHeaderValue("Totaal pakketten");
            
            
            
            
        }catch (SQLException ex) {
            System.out.println ("Er is iets mis met de database.");
            // Logger.getLogger(Blok4WC2.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
         

        
    }
    
    public void setOpener(HomeScreen a){
        this.opener = a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        myTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Return");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        myTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(myTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(357, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        HomeScreen hs = new HomeScreen();
        hs.setVisible(true);
        hs.setLocationRelativeTo(null);
        this.setVisible(false);
        if(hs == null){
            hs = new HomeScreen();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GegevensUitgiftepunt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GegevensUitgiftepunt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GegevensUitgiftepunt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GegevensUitgiftepunt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GegevensUitgiftepunt().setVisible(true);   
                
                
            }
        });
    }
    
     
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable myTable;
    // End of variables declaration//GEN-END:variables
}
